### PR TITLE
Rename `fasd` to `fad`

### PR DESCRIPTION
**Pull request by ryenus**
This is not a prank :-)

The new name `fad` can be simply interpreted as, **F**iles **A**nd **D**irectories, that are **F**recently **A**ccesse**D**.

The old name `fasd` is not friendly to search engines, and even (potential) new users, as `fasd` tends to be treated as a typo, thus ignored or misinterpreted by search engines and people unfamiliar with it.

Also making frequently used files and directories easier to access is somewhat close to a [_fad_](https://en.wikipedia.org/wiki/Fad) behavior. English is not my native tone, so you can close the gap with your imaginations.

Finally one can always use `alias fasd=fad` to ensure backward compatibility. Also GitHub can correctly redirect renamed repositories until the old name is occupied.

Your thoughts? please show your support if you like this idea :-)

### CODE REVIEW

**Comment by clvv** [comment]
Thank you for this thoughtful PR.

I like the proposal. However, I don't think the benefit warrants a name switch. As a commandline tool, fasd is not a big software project. I would like it to be trouble free. Renaming a repository causes troubles with people's git workflows.

As for SEO, I would recommend referring to fasd as clvv/fasd when posting on forums without a link. This will get this project page as the top result.

**Comment by andyleejordan** [comment]
I am in total support of this! :+1:

I like the tool a lot, but don't really like the name. It's just... FASD is a serious problem, and it just doesn't seem right to usurp the disorder's name.

Also, I think because

> fasd is not a big software project

right now is the best time to change the name.

Just casting another vote :smile: thanks for the excellent tool!

**Comment by alphapapa** [comment]
My 2 cents: `fasd` is far more distinctive than `fad`.  It's also somewhat mnemonic and descriptive.  I think renaming it would provide no benefit and would actually have a negative impact.

**Comment by malikoth** [comment]
Just weighing in.  I don't think there should be a name change, either.  clvv/fasd does not "usurp" the disorder's name, it's an acronym that happens to have multiple disambiguations.  This is why Wikipedia has disambiguation pages, often with dozens (or hundreds!) of entries.  (see: https://en.wikipedia.org/wiki/Ace_(disambiguation) )  That this tool helps me get to where I want to be in the filesystem "fast" is way more memorable to me than that it may track popular locations, like a fad.

**Comment by alphapapa** [comment]
FYI, searching Google for `fasd` lists this repo on the first page of results, so I don't think SEO is an issue anymore.

**Pull request closed without merging**
